[tools]
go = "1.25.6"
golangci-lint = "2.8.0"
awscli = "latest"

[env]
MISE_DISABLE_BACKENDS = "aqua,ubi"

[settings]
experimental = true

# Commands

[tasks.aiprompt]
run = "go run cmd/aiprompt/main.go cmd/aiprompt/.prompts"

[tasks.keygen]
run = "go run cmd/keygen/main.go"

[tasks.workplan]
run = "go run cmd/workplan/main.go"

# Linting

[tasks.lint]
run = "golangci-lint run --fix"

[tasks.format]
run = "go fmt ./..."

# Release

[tasks.start-release]
run = "./scripts/git-tag-release.sh"
